site: Joshua Fayer Blog
baseurl: ""
url: blog.joshuafayer.com
permalink: /:title/
collections:
  category:
    output: true
defaults:
  -
    scope:
      path: ""
      type: category
    values:
      layout: "category"
